### ISSUE TITLE
birds_eye_view function from example is not runnable

### ISSUE THREAD

**Issue by stevenlio88** [UBC-MDS/reasyeda#32]
birds_eye_view function from the example is not runnable. I got an error:

> Error in `dplyr::sym()`:
! Can't convert NULL to a symbol.
Backtrace:
> 1. reasyeda::birds_eye_view(toy_data)
> 8. dplyr::sym(names(categorical[, i]))

I am following the example as instructed in the README.

> library(reasyeda)
> library(palmerpenguins) # load the dataset

> ## basic example code
> clean_up(penguins)
> results <- birds_eye_view(penguins)
> close_up(penguins)
> summary_suggestions(penguins)

**Comment by khbunyan** [comment]
Hi Steven, thanks for reviewing our package and for raising this.

I noticed it references "toy_data" in the error, is this your own dataset? The function birds_eye_view only works properly with factor type categorical variables which is why we use the "penguins" dataset in the readme. I just re-ran on my machine, and it generated the charts.

Does it work properly for you with the penguins data set?

Thanks!

**Comment by Luming-ubc** [comment]
This issue could be resolved with the latest submission version.
